import { join } from 'path';
import type { ToolkitConfig } from '../core/types.js';
import { writeTextFile, fileExists, readTextFile } from '../utils/file-ops.js';
import { log } from '../utils/logger.js';

export async function syncEditorSettings(
  projectRoot: string,
  config: ToolkitConfig,
  dryRun: boolean,
): Promise<string[]> {
  const synced: string[] = [];

  if (!config.settings) return synced;

  // 1. Generate .editorconfig
  const editorConfigContent = generateEditorConfig(config);
  if (editorConfigContent) {
    const editorConfigPath = join(projectRoot, '.editorconfig');
    if (dryRun) {
      log.dryRun('would write', '.editorconfig');
    } else {
      await writeTextFile(editorConfigPath, editorConfigContent);
      log.synced('settings', '.editorconfig');
    }
    synced.push(editorConfigPath);
  }

  // 2. Merge into .vscode/settings.json
  const vscodeSettings = generateVSCodeSettings(config);
  if (vscodeSettings) {
    const vscodeSettingsPath = join(projectRoot, '.vscode', 'settings.json');
    if (dryRun) {
      log.dryRun('would merge', '.vscode/settings.json');
    } else {
      await mergeVSCodeSettings(vscodeSettingsPath, vscodeSettings);
      log.synced('settings', '.vscode/settings.json');
    }
    synced.push(vscodeSettingsPath);
  }

  return synced;
}

function generateEditorConfig(config: ToolkitConfig): string | null {
  const s = config.settings;
  if (!s) return null;

  const lines: string[] = [
    '# Generated by Chain',
    'root = true',
    '',
    '[*]',
  ];

  if (s.indent_style) lines.push(`indent_style = ${s.indent_style}`);
  if (s.indent_size) lines.push(`indent_size = ${s.indent_size}`);
  lines.push('end_of_line = lf');
  lines.push('charset = utf-8');
  lines.push('trim_trailing_whitespace = true');
  lines.push('insert_final_newline = true');
  lines.push('');

  return lines.join('\n');
}

function generateVSCodeSettings(config: ToolkitConfig): Record<string, unknown> | null {
  const s = config.settings;
  if (!s) return null;

  const settings: Record<string, unknown> = {};

  if (s.indent_size) {
    settings['editor.tabSize'] = s.indent_size;
  }
  if (s.indent_style) {
    settings['editor.insertSpaces'] = s.indent_style === 'space';
  }
  if (s.format_on_save !== undefined) {
    settings['editor.formatOnSave'] = s.format_on_save;
  }

  if (Object.keys(settings).length === 0) return null;
  return settings;
}

async function mergeVSCodeSettings(
  settingsPath: string,
  newSettings: Record<string, unknown>,
): Promise<void> {
  let existing: Record<string, unknown> = {};

  if (await fileExists(settingsPath)) {
    try {
      const content = await readTextFile(settingsPath);
      existing = JSON.parse(content);
    } catch {
      // Invalid JSON — overwrite
    }
  }

  const merged = { ...existing, ...newSettings };
  await writeTextFile(settingsPath, JSON.stringify(merged, null, 2) + '\n');
}
