import { z } from 'zod';

// ============================================
// Editor Definitions
// ============================================

export const EditorName = z.enum([
  'cursor',
  'windsurf',
  'claude',
  'kiro',
  'trae',
  'gemini',
  'copilot',
  'codex',
  'aider',
  'roo',
  'kilocode',
  'antigravity',
  'bolt',
  'warp',
]);
export type EditorName = z.infer<typeof EditorName>;

// ============================================
// Config Schema
// ============================================

export const MCP_ServerSchema = z.object({
  name: z.string(),
  command: z.string(),
  args: z.array(z.string()).optional(),
  env: z.record(z.string(), z.string()).optional(),
  enabled: z.boolean().optional().default(true),
});

export const EditorConfigSchema = z.union([
  z.boolean(),
  z.object({
    enabled: z.boolean().optional().default(true),
    output_path: z.string().optional(),
  }),
]);

export const CustomEditorSchema = z.object({
  name: z.string(),
  rules_dir: z.string(),
  skills_dir: z.string().optional(),
  workflows_dir: z.string().optional(),
  entry_point: z.string().optional(),
  mcp_config_path: z.string().optional(),
  file_naming: z.enum(['flat', 'subdirectory']).optional().default('flat'),
});

export type CustomEditorConfig = z.infer<typeof CustomEditorSchema>;

export const ContentSourceSchema = z.object({
  type: z.enum(['local', 'package']),
  path: z.string().optional(),
  name: z.string().optional(),
  include: z.array(z.enum(['rules', 'skills', 'workflows'])).optional(),
});

export type ContentSource = z.infer<typeof ContentSourceSchema>;

export const ToolkitConfigSchema = z.object({
  version: z.string().default('1.0'),

  editors: z.record(z.string(), EditorConfigSchema).optional().default({}),

  custom_editors: z.array(CustomEditorSchema).optional(),

  extends: z.array(z.string()).optional(),

  metadata: z
    .object({
      name: z.string().optional(),
      description: z.string().optional(),
    })
    .optional(),

  tech_stack: z
    .object({
      language: z.string().optional(),
      framework: z.string().optional(),
      database: z.string().optional(),
      runtime: z.string().optional(),
    })
    .optional(),

  mcp_servers: z.array(MCP_ServerSchema).optional(),

  settings: z
    .object({
      indent_size: z.number().optional(),
      indent_style: z.enum(['space', 'tab']).optional(),
      format_on_save: z.boolean().optional(),
    })
    .catchall(z.unknown())
    .optional(),

  ignore_patterns: z.array(z.string()).optional(),

  content_sources: z.array(ContentSourceSchema).optional(),
});

export type ToolkitConfig = z.infer<typeof ToolkitConfigSchema>;
export type MCPServer = z.infer<typeof MCP_ServerSchema>;

// ============================================
// Editor Adapter Interface
// ============================================

export interface EditorDirectories {
  rules: string;
  skills?: string;
  workflows?: string;
}

export interface EditorAdapter {
  name: string;
  directories: EditorDirectories;
  entryPoint?: string;
  mcpConfigPath?: string;
  fileNaming: 'flat' | 'subdirectory';
  generateFrontmatter?: (skillName: string, description?: string) => string;
  generateEntryPointContent?: (config: ToolkitConfig) => string;
}

// ============================================
// Sync Types
// ============================================

export interface SyncOptions {
  dryRun?: boolean;
  verbose?: boolean;
  yes?: boolean;
  autoRemoveOrphans?: boolean;
}

export interface OrphanedFile {
  relativePath: string;
  absolutePath: string;
}

export interface SsotOrphan {
  category: string;
  name: string;
  absolutePath: string;
}

export interface SsotDiff {
  category: string;
  name: string;
  localPath: string;
  ssotPath: string;
  direction: 'local-newer' | 'ssot-newer';
}

export interface SyncResult {
  synced: string[];
  skipped: string[];
  removed: string[];
  errors: string[];
  pendingOrphans: OrphanedFile[];
  ssotOrphans: SsotOrphan[];
  ssotDiffs: SsotDiff[];
}

export interface ContentFile {
  name: string;
  relativePath: string;
  absolutePath: string;
  content: string;
}

// ============================================
// Constants
// ============================================

export const CONFIG_FILENAME = 'chain.yaml';
export const CONTENT_DIR = '.chain';
export const SKILLS_DIR = 'skills';
export const RULES_DIR = 'rules';
export const WORKFLOWS_DIR = 'workflows';
export const OVERRIDES_DIR = 'overrides';
export const PROJECT_CONTEXT_FILE = 'PROJECT.md';


export const AUTO_GENERATED_MARKER =
  '<!-- ⚠️ AUTO-GENERATED by chain — DO NOT EDIT -->';
export const SOURCE_MARKER_PREFIX = '<!-- Source:';
